// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class EnumNotifyType {
  private EnumNotifyType() {}
  // enum ENotifyType
  public static final int LOGOUT_NOTIFY = 1;
  public static final int CONFIG_CHANGED_NOTIFY = 2;
  public static final int UPLOAD_LOG_NOTIFY = 3;

}
