// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class EnumPacketType {
  private EnumPacketType() {}
  // enum EPacketType
  public static final int REQUEST = 1;
  public static final int RESPONSE = 2;
  public static final int NOTIFYCATION = 3;
  public static final int CUSTOM = 4;

}
