// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class EnumPushconfirmResult {
  private EnumPushconfirmResult() {}
  // enum EPushConfirmResult
  public static final int CONFIRM_SUCCESS = 0;
  public static final int CONFIRM_PARAM_ERROR = 10400;
  public static final int CONFIRM_SERVER_ERROR = 10401;
  public static final int CONFIRM_HALF_SUCCESS = 10402;

}
