// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class EnumChannelStatus {
  private EnumChannelStatus() {}
  // enum EChannelStatus
  public static final int CHANNEL_UNLINK = 1;
  public static final int CHANNEL_NORMAL = 2;

}
