// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class EnumUserStatus {
  private EnumUserStatus() {}
  // enum EUserStatus
  public static final int USER_NULL = 1;
  public static final int USER_ONLINE = 2;
  public static final int USER_OFFLINE = 3;

}
