// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class EnumPlatformType {
  private EnumPlatformType() {}
  // enum EPlatformType
  public static final int WINDOWS = 1;
  public static final int MAC = 2;
  public static final int _NIX = 4;
  public static final int ANDROID = 8;
  public static final int IOS = 16;
  public static final int WP = 32;
  public static final int WEB = 64;
  public static final int WINDOW_MOBILE = 128;

}
