// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class EnumApnInfo {
  private EnumApnInfo() {}
  // enum EAPNInfo
  public static final int CHINA_MOBILE = 1;
  public static final int CHINA_UNICOM = 2;
  public static final int CHINA_TELECOM = 3;
  public static final int OTHER = 4;
  public static final int NETWORK_UNKNOWN = 5;

}
