// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class EnumChatType {
  private EnumChatType() {}
  // enum EChatType
  public static final int CHAT_P2P = 1;
  public static final int CHAT_P2G = 2;
  public static final int CHAT_PA = 3;

}
