// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class EnumMessageType {
  private EnumMessageType() {}
  // enum EMessageType
  public static final int NORMAL_MSG = 1;
  public static final int SYS_NOTIFY_MSG = 2;

}
