// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class EnumFileType {
  private EnumFileType() {}
  // enum EFileType
  public static final int FILE_IMAGE = 1;
  public static final int FILE_VOICE = 2;
  public static final int FILE_CUSTOM = 3;

}
