// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class EnumNetworkType {
  private EnumNetworkType() {}
  // enum ENetworkType
  public static final int APN_WWW = 1;
  public static final int APN_WIFI = 2;
  public static final int APN_2G = 3;
  public static final int APN_3G = 4;
  public static final int APN_4G = 5;
  public static final int APN_UNKNOWN = 6;

}
