// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class ObjConfigGroup {
  private ObjConfigGroup() {}
  @SuppressWarnings("hiding")
  public static final class ConfigGroup extends
      com.google.protobuf.micro.MessageMicro {
    public ConfigGroup() {}

    // required string groupName = 1;
    public static final int GROUPNAME_FIELD_NUMBER = 1;
    private boolean hasGroupName;
    private java.lang.String groupName_ = "";
    public java.lang.String getGroupName() { return groupName_; }
    public boolean hasGroupName() { return hasGroupName; }
    public ConfigGroup setGroupName(java.lang.String value) {
      hasGroupName = true;
      groupName_ = value;
      return this;
    }
    public ConfigGroup clearGroupName() {
      hasGroupName = false;
      groupName_ = "";
      return this;
    }

    // required string md5 = 2;
    public static final int MD5_FIELD_NUMBER = 2;
    private boolean hasMd5;
    private java.lang.String md5_ = "";
    public java.lang.String getMd5() { return md5_; }
    public boolean hasMd5() { return hasMd5; }
    public ConfigGroup setMd5(java.lang.String value) {
      hasMd5 = true;
      md5_ = value;
      return this;
    }
    public ConfigGroup clearMd5() {
      hasMd5 = false;
      md5_ = "";
      return this;
    }

    // optional string configJson = 3;
    public static final int CONFIGJSON_FIELD_NUMBER = 3;
    private boolean hasConfigJson;
    private java.lang.String configJson_ = "";
    public java.lang.String getConfigJson() { return configJson_; }
    public boolean hasConfigJson() { return hasConfigJson; }
    public ConfigGroup setConfigJson(java.lang.String value) {
      hasConfigJson = true;
      configJson_ = value;
      return this;
    }
    public ConfigGroup clearConfigJson() {
      hasConfigJson = false;
      configJson_ = "";
      return this;
    }

    public final ConfigGroup clear() {
      clearGroupName();
      clearMd5();
      clearConfigJson();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasGroupName) return false;
      if (!hasMd5) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasGroupName()) {
        output.writeString(1, getGroupName());
      }
      if (hasMd5()) {
        output.writeString(2, getMd5());
      }
      if (hasConfigJson()) {
        output.writeString(3, getConfigJson());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasGroupName()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(1, getGroupName());
      }
      if (hasMd5()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(2, getMd5());
      }
      if (hasConfigJson()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(3, getConfigJson());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public ConfigGroup mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            setGroupName(input.readString());
            break;
          }
          case 18: {
            setMd5(input.readString());
            break;
          }
          case 26: {
            setConfigJson(input.readString());
            break;
          }
        }
      }
    }

    public static ConfigGroup parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (ConfigGroup) (new ConfigGroup().mergeFrom(data));
    }

    public static ConfigGroup parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new ConfigGroup().mergeFrom(input);
    }

  }

}
