// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class ObjChatConversation {
  private ObjChatConversation() {}
  @SuppressWarnings("hiding")
  public static final class ChatConversation extends
      com.google.protobuf.micro.MessageMicro {
    public ChatConversation() {}

    // required .EChatType chatType = 1;
    public static final int CHATTYPE_FIELD_NUMBER = 1;
    private boolean hasChatType;
    private int chatType_ = com.baidu.im.frame.pb.EnumChatType.CHAT_P2P;
    public boolean hasChatType() { return hasChatType; }
    public int getChatType() { return chatType_; }
    public ChatConversation setChatType(int value) {
      hasChatType = true;
      chatType_ = value;
      return this;
    }
    public ChatConversation clearChatType() {
      hasChatType = false;
      chatType_ = com.baidu.im.frame.pb.EnumChatType.CHAT_P2P;
      return this;
    }

    // required string chatId = 2;
    public static final int CHATID_FIELD_NUMBER = 2;
    private boolean hasChatId;
    private java.lang.String chatId_ = "";
    public java.lang.String getChatId() { return chatId_; }
    public boolean hasChatId() { return hasChatId; }
    public ChatConversation setChatId(java.lang.String value) {
      hasChatId = true;
      chatId_ = value;
      return this;
    }
    public ChatConversation clearChatId() {
      hasChatId = false;
      chatId_ = "";
      return this;
    }

    // required uint64 lastRecvMsgSeq = 3;
    public static final int LASTRECVMSGSEQ_FIELD_NUMBER = 3;
    private boolean hasLastRecvMsgSeq;
    private long lastRecvMsgSeq_ = 0L;
    public long getLastRecvMsgSeq() { return lastRecvMsgSeq_; }
    public boolean hasLastRecvMsgSeq() { return hasLastRecvMsgSeq; }
    public ChatConversation setLastRecvMsgSeq(long value) {
      hasLastRecvMsgSeq = true;
      lastRecvMsgSeq_ = value;
      return this;
    }
    public ChatConversation clearLastRecvMsgSeq() {
      hasLastRecvMsgSeq = false;
      lastRecvMsgSeq_ = 0L;
      return this;
    }

    // required uint64 lastRecvMsgTime = 4;
    public static final int LASTRECVMSGTIME_FIELD_NUMBER = 4;
    private boolean hasLastRecvMsgTime;
    private long lastRecvMsgTime_ = 0L;
    public long getLastRecvMsgTime() { return lastRecvMsgTime_; }
    public boolean hasLastRecvMsgTime() { return hasLastRecvMsgTime; }
    public ChatConversation setLastRecvMsgTime(long value) {
      hasLastRecvMsgTime = true;
      lastRecvMsgTime_ = value;
      return this;
    }
    public ChatConversation clearLastRecvMsgTime() {
      hasLastRecvMsgTime = false;
      lastRecvMsgTime_ = 0L;
      return this;
    }

    // required uint64 lastReadMsgSeq = 5;
    public static final int LASTREADMSGSEQ_FIELD_NUMBER = 5;
    private boolean hasLastReadMsgSeq;
    private long lastReadMsgSeq_ = 0L;
    public long getLastReadMsgSeq() { return lastReadMsgSeq_; }
    public boolean hasLastReadMsgSeq() { return hasLastReadMsgSeq; }
    public ChatConversation setLastReadMsgSeq(long value) {
      hasLastReadMsgSeq = true;
      lastReadMsgSeq_ = value;
      return this;
    }
    public ChatConversation clearLastReadMsgSeq() {
      hasLastReadMsgSeq = false;
      lastReadMsgSeq_ = 0L;
      return this;
    }

    // required uint64 lastReadMsgTime = 6;
    public static final int LASTREADMSGTIME_FIELD_NUMBER = 6;
    private boolean hasLastReadMsgTime;
    private long lastReadMsgTime_ = 0L;
    public long getLastReadMsgTime() { return lastReadMsgTime_; }
    public boolean hasLastReadMsgTime() { return hasLastReadMsgTime; }
    public ChatConversation setLastReadMsgTime(long value) {
      hasLastReadMsgTime = true;
      lastReadMsgTime_ = value;
      return this;
    }
    public ChatConversation clearLastReadMsgTime() {
      hasLastReadMsgTime = false;
      lastReadMsgTime_ = 0L;
      return this;
    }

    public final ChatConversation clear() {
      clearChatType();
      clearChatId();
      clearLastRecvMsgSeq();
      clearLastRecvMsgTime();
      clearLastReadMsgSeq();
      clearLastReadMsgTime();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasChatType) return false;
      if (!hasChatId) return false;
      if (!hasLastRecvMsgSeq) return false;
      if (!hasLastRecvMsgTime) return false;
      if (!hasLastReadMsgSeq) return false;
      if (!hasLastReadMsgTime) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasChatType()) {
        output.writeInt32(1, getChatType());
      }
      if (hasChatId()) {
        output.writeString(2, getChatId());
      }
      if (hasLastRecvMsgSeq()) {
        output.writeUInt64(3, getLastRecvMsgSeq());
      }
      if (hasLastRecvMsgTime()) {
        output.writeUInt64(4, getLastRecvMsgTime());
      }
      if (hasLastReadMsgSeq()) {
        output.writeUInt64(5, getLastReadMsgSeq());
      }
      if (hasLastReadMsgTime()) {
        output.writeUInt64(6, getLastReadMsgTime());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasChatType()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeInt32Size(1, getChatType());
      }
      if (hasChatId()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(2, getChatId());
      }
      if (hasLastRecvMsgSeq()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt64Size(3, getLastRecvMsgSeq());
      }
      if (hasLastRecvMsgTime()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt64Size(4, getLastRecvMsgTime());
      }
      if (hasLastReadMsgSeq()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt64Size(5, getLastReadMsgSeq());
      }
      if (hasLastReadMsgTime()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt64Size(6, getLastReadMsgTime());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public ChatConversation mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
              setChatType(input.readInt32());
            break;
          }
          case 18: {
            setChatId(input.readString());
            break;
          }
          case 24: {
            setLastRecvMsgSeq(input.readUInt64());
            break;
          }
          case 32: {
            setLastRecvMsgTime(input.readUInt64());
            break;
          }
          case 40: {
            setLastReadMsgSeq(input.readUInt64());
            break;
          }
          case 48: {
            setLastReadMsgTime(input.readUInt64());
            break;
          }
        }
      }
    }

    public static ChatConversation parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (ChatConversation) (new ChatConversation().mergeFrom(data));
    }

    public static ChatConversation parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new ChatConversation().mergeFrom(input);
    }

  }

}
