// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class ObjDownPacket {
  private ObjDownPacket() {}
  @SuppressWarnings("hiding")
  public static final class DownPacket extends
      com.google.protobuf.micro.MessageMicro {
    public DownPacket() {}

    // optional string sessionId = 1;
    public static final int SESSIONID_FIELD_NUMBER = 1;
    private boolean hasSessionId;
    private java.lang.String sessionId_ = "";
    public java.lang.String getSessionId() { return sessionId_; }
    public boolean hasSessionId() { return hasSessionId; }
    public DownPacket setSessionId(java.lang.String value) {
      hasSessionId = true;
      sessionId_ = value;
      return this;
    }
    public DownPacket clearSessionId() {
      hasSessionId = false;
      sessionId_ = "";
      return this;
    }

    // required uint32 seq = 2;
    public static final int SEQ_FIELD_NUMBER = 2;
    private boolean hasSeq;
    private int seq_ = 0;
    public int getSeq() { return seq_; }
    public boolean hasSeq() { return hasSeq; }
    public DownPacket setSeq(int value) {
      hasSeq = true;
      seq_ = value;
      return this;
    }
    public DownPacket clearSeq() {
      hasSeq = false;
      seq_ = 0;
      return this;
    }

    // required int32 channelCode = 3;
    public static final int CHANNELCODE_FIELD_NUMBER = 3;
    private boolean hasChannelCode;
    private int channelCode_ = 0;
    public int getChannelCode() { return channelCode_; }
    public boolean hasChannelCode() { return hasChannelCode; }
    public DownPacket setChannelCode(int value) {
      hasChannelCode = true;
      channelCode_ = value;
      return this;
    }
    public DownPacket clearChannelCode() {
      hasChannelCode = false;
      channelCode_ = 0;
      return this;
    }

    // optional uint64 uid = 4;
    public static final int UID_FIELD_NUMBER = 4;
    private boolean hasUid;
    private long uid_ = 0L;
    public long getUid() { return uid_; }
    public boolean hasUid() { return hasUid; }
    public DownPacket setUid(long value) {
      hasUid = true;
      uid_ = value;
      return this;
    }
    public DownPacket clearUid() {
      hasUid = false;
      uid_ = 0L;
      return this;
    }

    // optional uint32 appId = 5;
    public static final int APPID_FIELD_NUMBER = 5;
    private boolean hasAppId;
    private int appId_ = 0;
    public int getAppId() { return appId_; }
    public boolean hasAppId() { return hasAppId; }
    public DownPacket setAppId(int value) {
      hasAppId = true;
      appId_ = value;
      return this;
    }
    public DownPacket clearAppId() {
      hasAppId = false;
      appId_ = 0;
      return this;
    }

    // optional .BizDownPackage bizPackage = 6;
    public static final int BIZPACKAGE_FIELD_NUMBER = 6;
    private boolean hasBizPackage;
    private com.baidu.im.frame.pb.ObjBizDownPacket.BizDownPackage bizPackage_ = null;
    public boolean hasBizPackage() { return hasBizPackage; }
    public com.baidu.im.frame.pb.ObjBizDownPacket.BizDownPackage getBizPackage() { return bizPackage_; }
    public DownPacket setBizPackage(com.baidu.im.frame.pb.ObjBizDownPacket.BizDownPackage value) {
      if (value == null) {
        throw new NullPointerException();
      }
      hasBizPackage = true;
      bizPackage_ = value;
      return this;
    }
    public DownPacket clearBizPackage() {
      hasBizPackage = false;
      bizPackage_ = null;
      return this;
    }

    public final DownPacket clear() {
      clearSessionId();
      clearSeq();
      clearChannelCode();
      clearUid();
      clearAppId();
      clearBizPackage();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasSeq) return false;
      if (!hasChannelCode) return false;
      if (hasBizPackage()) {
        if (!getBizPackage().isInitialized()) return false;
      }
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasSessionId()) {
        output.writeString(1, getSessionId());
      }
      if (hasSeq()) {
        output.writeUInt32(2, getSeq());
      }
      if (hasChannelCode()) {
        output.writeInt32(3, getChannelCode());
      }
      if (hasUid()) {
        output.writeUInt64(4, getUid());
      }
      if (hasAppId()) {
        output.writeUInt32(5, getAppId());
      }
      if (hasBizPackage()) {
        output.writeMessage(6, getBizPackage());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasSessionId()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(1, getSessionId());
      }
      if (hasSeq()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt32Size(2, getSeq());
      }
      if (hasChannelCode()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeInt32Size(3, getChannelCode());
      }
      if (hasUid()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt64Size(4, getUid());
      }
      if (hasAppId()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt32Size(5, getAppId());
      }
      if (hasBizPackage()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(6, getBizPackage());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public DownPacket mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            setSessionId(input.readString());
            break;
          }
          case 16: {
            setSeq(input.readUInt32());
            break;
          }
          case 24: {
            setChannelCode(input.readInt32());
            break;
          }
          case 32: {
            setUid(input.readUInt64());
            break;
          }
          case 40: {
            setAppId(input.readUInt32());
            break;
          }
          case 50: {
            com.baidu.im.frame.pb.ObjBizDownPacket.BizDownPackage value = new com.baidu.im.frame.pb.ObjBizDownPacket.BizDownPackage();
            input.readMessage(value);
            setBizPackage(value);
            break;
          }
        }
      }
    }

    public static DownPacket parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (DownPacket) (new DownPacket().mergeFrom(data));
    }

    public static DownPacket parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new DownPacket().mergeFrom(input);
    }

  }

}
