// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class ObjImage {
  private ObjImage() {}
  @SuppressWarnings("hiding")
  public static final class Image extends
      com.google.protobuf.micro.MessageMicro {
    public Image() {}

    // optional string imageId = 1;
    public static final int IMAGEID_FIELD_NUMBER = 1;
    private boolean hasImageId;
    private java.lang.String imageId_ = "";
    public java.lang.String getImageId() { return imageId_; }
    public boolean hasImageId() { return hasImageId; }
    public Image setImageId(java.lang.String value) {
      hasImageId = true;
      imageId_ = value;
      return this;
    }
    public Image clearImageId() {
      hasImageId = false;
      imageId_ = "";
      return this;
    }

    // required string md5 = 2;
    public static final int MD5_FIELD_NUMBER = 2;
    private boolean hasMd5;
    private java.lang.String md5_ = "";
    public java.lang.String getMd5() { return md5_; }
    public boolean hasMd5() { return hasMd5; }
    public Image setMd5(java.lang.String value) {
      hasMd5 = true;
      md5_ = value;
      return this;
    }
    public Image clearMd5() {
      hasMd5 = false;
      md5_ = "";
      return this;
    }

    // required uint32 size = 3;
    public static final int SIZE_FIELD_NUMBER = 3;
    private boolean hasSize;
    private int size_ = 0;
    public int getSize() { return size_; }
    public boolean hasSize() { return hasSize; }
    public Image setSize(int value) {
      hasSize = true;
      size_ = value;
      return this;
    }
    public Image clearSize() {
      hasSize = false;
      size_ = 0;
      return this;
    }

    // required uint32 width = 4;
    public static final int WIDTH_FIELD_NUMBER = 4;
    private boolean hasWidth;
    private int width_ = 0;
    public int getWidth() { return width_; }
    public boolean hasWidth() { return hasWidth; }
    public Image setWidth(int value) {
      hasWidth = true;
      width_ = value;
      return this;
    }
    public Image clearWidth() {
      hasWidth = false;
      width_ = 0;
      return this;
    }

    // required uint32 height = 5;
    public static final int HEIGHT_FIELD_NUMBER = 5;
    private boolean hasHeight;
    private int height_ = 0;
    public int getHeight() { return height_; }
    public boolean hasHeight() { return hasHeight; }
    public Image setHeight(int value) {
      hasHeight = true;
      height_ = value;
      return this;
    }
    public Image clearHeight() {
      hasHeight = false;
      height_ = 0;
      return this;
    }

    // optional string url = 6;
    public static final int URL_FIELD_NUMBER = 6;
    private boolean hasUrl;
    private java.lang.String url_ = "";
    public java.lang.String getUrl() { return url_; }
    public boolean hasUrl() { return hasUrl; }
    public Image setUrl(java.lang.String value) {
      hasUrl = true;
      url_ = value;
      return this;
    }
    public Image clearUrl() {
      hasUrl = false;
      url_ = "";
      return this;
    }

    // optional string extInfo = 7;
    public static final int EXTINFO_FIELD_NUMBER = 7;
    private boolean hasExtInfo;
    private java.lang.String extInfo_ = "";
    public java.lang.String getExtInfo() { return extInfo_; }
    public boolean hasExtInfo() { return hasExtInfo; }
    public Image setExtInfo(java.lang.String value) {
      hasExtInfo = true;
      extInfo_ = value;
      return this;
    }
    public Image clearExtInfo() {
      hasExtInfo = false;
      extInfo_ = "";
      return this;
    }

    public final Image clear() {
      clearImageId();
      clearMd5();
      clearSize();
      clearWidth();
      clearHeight();
      clearUrl();
      clearExtInfo();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasMd5) return false;
      if (!hasSize) return false;
      if (!hasWidth) return false;
      if (!hasHeight) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasImageId()) {
        output.writeString(1, getImageId());
      }
      if (hasMd5()) {
        output.writeString(2, getMd5());
      }
      if (hasSize()) {
        output.writeUInt32(3, getSize());
      }
      if (hasWidth()) {
        output.writeUInt32(4, getWidth());
      }
      if (hasHeight()) {
        output.writeUInt32(5, getHeight());
      }
      if (hasUrl()) {
        output.writeString(6, getUrl());
      }
      if (hasExtInfo()) {
        output.writeString(7, getExtInfo());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasImageId()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(1, getImageId());
      }
      if (hasMd5()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(2, getMd5());
      }
      if (hasSize()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt32Size(3, getSize());
      }
      if (hasWidth()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt32Size(4, getWidth());
      }
      if (hasHeight()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt32Size(5, getHeight());
      }
      if (hasUrl()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(6, getUrl());
      }
      if (hasExtInfo()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(7, getExtInfo());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public Image mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            setImageId(input.readString());
            break;
          }
          case 18: {
            setMd5(input.readString());
            break;
          }
          case 24: {
            setSize(input.readUInt32());
            break;
          }
          case 32: {
            setWidth(input.readUInt32());
            break;
          }
          case 40: {
            setHeight(input.readUInt32());
            break;
          }
          case 50: {
            setUrl(input.readString());
            break;
          }
          case 58: {
            setExtInfo(input.readString());
            break;
          }
        }
      }
    }

    public static Image parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (Image) (new Image().mergeFrom(data));
    }

    public static Image parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new Image().mergeFrom(input);
    }

  }

}
