// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class ObjMsgContent {
  private ObjMsgContent() {}
  @SuppressWarnings("hiding")
  public static final class MsgContent extends
      com.google.protobuf.micro.MessageMicro {
    public MsgContent() {}

    // repeated .Image images = 1;
    public static final int IMAGES_FIELD_NUMBER = 1;
    private java.util.List<com.baidu.im.frame.pb.ObjImage.Image> images_ =
      java.util.Collections.emptyList();
    public java.util.List<com.baidu.im.frame.pb.ObjImage.Image> getImagesList() {
      return images_;
    }
    public int getImagesCount() { return images_.size(); }
    public com.baidu.im.frame.pb.ObjImage.Image getImages(int index) {
      return images_.get(index);
    }
    public MsgContent setImages(int index, com.baidu.im.frame.pb.ObjImage.Image value) {
      if (value == null) {
        throw new NullPointerException();
      }
      images_.set(index, value);
      return this;
    }
    public MsgContent addImages(com.baidu.im.frame.pb.ObjImage.Image value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (images_.isEmpty()) {
        images_ = new java.util.ArrayList<com.baidu.im.frame.pb.ObjImage.Image>();
      }
      images_.add(value);
      return this;
    }
    public MsgContent clearImages() {
      images_ = java.util.Collections.emptyList();
      return this;
    }

    // repeated .Voice voices = 2;
    public static final int VOICES_FIELD_NUMBER = 2;
    private java.util.List<com.baidu.im.frame.pb.ObjVoice.Voice> voices_ =
      java.util.Collections.emptyList();
    public java.util.List<com.baidu.im.frame.pb.ObjVoice.Voice> getVoicesList() {
      return voices_;
    }
    public int getVoicesCount() { return voices_.size(); }
    public com.baidu.im.frame.pb.ObjVoice.Voice getVoices(int index) {
      return voices_.get(index);
    }
    public MsgContent setVoices(int index, com.baidu.im.frame.pb.ObjVoice.Voice value) {
      if (value == null) {
        throw new NullPointerException();
      }
      voices_.set(index, value);
      return this;
    }
    public MsgContent addVoices(com.baidu.im.frame.pb.ObjVoice.Voice value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (voices_.isEmpty()) {
        voices_ = new java.util.ArrayList<com.baidu.im.frame.pb.ObjVoice.Voice>();
      }
      voices_.add(value);
      return this;
    }
    public MsgContent clearVoices() {
      voices_ = java.util.Collections.emptyList();
      return this;
    }

    // repeated .File files = 3;
    public static final int FILES_FIELD_NUMBER = 3;
    private java.util.List<com.baidu.im.frame.pb.ObjFile.File> files_ =
      java.util.Collections.emptyList();
    public java.util.List<com.baidu.im.frame.pb.ObjFile.File> getFilesList() {
      return files_;
    }
    public int getFilesCount() { return files_.size(); }
    public com.baidu.im.frame.pb.ObjFile.File getFiles(int index) {
      return files_.get(index);
    }
    public MsgContent setFiles(int index, com.baidu.im.frame.pb.ObjFile.File value) {
      if (value == null) {
        throw new NullPointerException();
      }
      files_.set(index, value);
      return this;
    }
    public MsgContent addFiles(com.baidu.im.frame.pb.ObjFile.File value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (files_.isEmpty()) {
        files_ = new java.util.ArrayList<com.baidu.im.frame.pb.ObjFile.File>();
      }
      files_.add(value);
      return this;
    }
    public MsgContent clearFiles() {
      files_ = java.util.Collections.emptyList();
      return this;
    }

    // repeated .Text texts = 4;
    public static final int TEXTS_FIELD_NUMBER = 4;
    private java.util.List<com.baidu.im.frame.pb.ObjText.Text> texts_ =
      java.util.Collections.emptyList();
    public java.util.List<com.baidu.im.frame.pb.ObjText.Text> getTextsList() {
      return texts_;
    }
    public int getTextsCount() { return texts_.size(); }
    public com.baidu.im.frame.pb.ObjText.Text getTexts(int index) {
      return texts_.get(index);
    }
    public MsgContent setTexts(int index, com.baidu.im.frame.pb.ObjText.Text value) {
      if (value == null) {
        throw new NullPointerException();
      }
      texts_.set(index, value);
      return this;
    }
    public MsgContent addTexts(com.baidu.im.frame.pb.ObjText.Text value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (texts_.isEmpty()) {
        texts_ = new java.util.ArrayList<com.baidu.im.frame.pb.ObjText.Text>();
      }
      texts_.add(value);
      return this;
    }
    public MsgContent clearTexts() {
      texts_ = java.util.Collections.emptyList();
      return this;
    }

    // repeated .URL urls = 5;
    public static final int URLS_FIELD_NUMBER = 5;
    private java.util.List<com.baidu.im.frame.pb.ObjUrl.URL> urls_ =
      java.util.Collections.emptyList();
    public java.util.List<com.baidu.im.frame.pb.ObjUrl.URL> getUrlsList() {
      return urls_;
    }
    public int getUrlsCount() { return urls_.size(); }
    public com.baidu.im.frame.pb.ObjUrl.URL getUrls(int index) {
      return urls_.get(index);
    }
    public MsgContent setUrls(int index, com.baidu.im.frame.pb.ObjUrl.URL value) {
      if (value == null) {
        throw new NullPointerException();
      }
      urls_.set(index, value);
      return this;
    }
    public MsgContent addUrls(com.baidu.im.frame.pb.ObjUrl.URL value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (urls_.isEmpty()) {
        urls_ = new java.util.ArrayList<com.baidu.im.frame.pb.ObjUrl.URL>();
      }
      urls_.add(value);
      return this;
    }
    public MsgContent clearUrls() {
      urls_ = java.util.Collections.emptyList();
      return this;
    }

    // repeated .Data datas = 6;
    public static final int DATAS_FIELD_NUMBER = 6;
    private java.util.List<com.baidu.im.frame.pb.ObjData.Data> datas_ =
      java.util.Collections.emptyList();
    public java.util.List<com.baidu.im.frame.pb.ObjData.Data> getDatasList() {
      return datas_;
    }
    public int getDatasCount() { return datas_.size(); }
    public com.baidu.im.frame.pb.ObjData.Data getDatas(int index) {
      return datas_.get(index);
    }
    public MsgContent setDatas(int index, com.baidu.im.frame.pb.ObjData.Data value) {
      if (value == null) {
        throw new NullPointerException();
      }
      datas_.set(index, value);
      return this;
    }
    public MsgContent addDatas(com.baidu.im.frame.pb.ObjData.Data value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (datas_.isEmpty()) {
        datas_ = new java.util.ArrayList<com.baidu.im.frame.pb.ObjData.Data>();
      }
      datas_.add(value);
      return this;
    }
    public MsgContent clearDatas() {
      datas_ = java.util.Collections.emptyList();
      return this;
    }

    // repeated bytes extContent = 7;
    public static final int EXTCONTENT_FIELD_NUMBER = 7;
    private java.util.List<com.google.protobuf.micro.ByteStringMicro> extContent_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protobuf.micro.ByteStringMicro> getExtContentList() {
      return extContent_;
    }
    public int getExtContentCount() { return extContent_.size(); }
    public com.google.protobuf.micro.ByteStringMicro getExtContent(int index) {
      return extContent_.get(index);
    }
    public MsgContent setExtContent(int index, com.google.protobuf.micro.ByteStringMicro value) {
      if (value == null) {
    throw new NullPointerException();
  }
  extContent_.set(index, value);
      return this;
    }
    public MsgContent addExtContent(com.google.protobuf.micro.ByteStringMicro value) {
      if (value == null) {
    throw new NullPointerException();
  }
  if (extContent_.isEmpty()) {
        extContent_ = new java.util.ArrayList<com.google.protobuf.micro.ByteStringMicro>();
      }
      extContent_.add(value);
      return this;
    }
    public MsgContent clearExtContent() {
      extContent_ = java.util.Collections.emptyList();
      return this;
    }

    public final MsgContent clear() {
      clearImages();
      clearVoices();
      clearFiles();
      clearTexts();
      clearUrls();
      clearDatas();
      clearExtContent();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      for (com.baidu.im.frame.pb.ObjImage.Image element : getImagesList()) {
        if (!element.isInitialized()) return false;
      }
      for (com.baidu.im.frame.pb.ObjVoice.Voice element : getVoicesList()) {
        if (!element.isInitialized()) return false;
      }
      for (com.baidu.im.frame.pb.ObjFile.File element : getFilesList()) {
        if (!element.isInitialized()) return false;
      }
      for (com.baidu.im.frame.pb.ObjText.Text element : getTextsList()) {
        if (!element.isInitialized()) return false;
      }
      for (com.baidu.im.frame.pb.ObjUrl.URL element : getUrlsList()) {
        if (!element.isInitialized()) return false;
      }
      for (com.baidu.im.frame.pb.ObjData.Data element : getDatasList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      for (com.baidu.im.frame.pb.ObjImage.Image element : getImagesList()) {
        output.writeMessage(1, element);
      }
      for (com.baidu.im.frame.pb.ObjVoice.Voice element : getVoicesList()) {
        output.writeMessage(2, element);
      }
      for (com.baidu.im.frame.pb.ObjFile.File element : getFilesList()) {
        output.writeMessage(3, element);
      }
      for (com.baidu.im.frame.pb.ObjText.Text element : getTextsList()) {
        output.writeMessage(4, element);
      }
      for (com.baidu.im.frame.pb.ObjUrl.URL element : getUrlsList()) {
        output.writeMessage(5, element);
      }
      for (com.baidu.im.frame.pb.ObjData.Data element : getDatasList()) {
        output.writeMessage(6, element);
      }
      for (com.google.protobuf.micro.ByteStringMicro element : getExtContentList()) {
        output.writeBytes(7, element);
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      for (com.baidu.im.frame.pb.ObjImage.Image element : getImagesList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(1, element);
      }
      for (com.baidu.im.frame.pb.ObjVoice.Voice element : getVoicesList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(2, element);
      }
      for (com.baidu.im.frame.pb.ObjFile.File element : getFilesList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(3, element);
      }
      for (com.baidu.im.frame.pb.ObjText.Text element : getTextsList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(4, element);
      }
      for (com.baidu.im.frame.pb.ObjUrl.URL element : getUrlsList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(5, element);
      }
      for (com.baidu.im.frame.pb.ObjData.Data element : getDatasList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(6, element);
      }
      {
        int dataSize = 0;
        for (com.google.protobuf.micro.ByteStringMicro element : getExtContentList()) {
          dataSize += com.google.protobuf.micro.CodedOutputStreamMicro
            .computeBytesSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getExtContentList().size();
      }
      cachedSize = size;
      return size;
    }

    @Override
    public MsgContent mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            com.baidu.im.frame.pb.ObjImage.Image value = new com.baidu.im.frame.pb.ObjImage.Image();
            input.readMessage(value);
            addImages(value);
            break;
          }
          case 18: {
            com.baidu.im.frame.pb.ObjVoice.Voice value = new com.baidu.im.frame.pb.ObjVoice.Voice();
            input.readMessage(value);
            addVoices(value);
            break;
          }
          case 26: {
            com.baidu.im.frame.pb.ObjFile.File value = new com.baidu.im.frame.pb.ObjFile.File();
            input.readMessage(value);
            addFiles(value);
            break;
          }
          case 34: {
            com.baidu.im.frame.pb.ObjText.Text value = new com.baidu.im.frame.pb.ObjText.Text();
            input.readMessage(value);
            addTexts(value);
            break;
          }
          case 42: {
            com.baidu.im.frame.pb.ObjUrl.URL value = new com.baidu.im.frame.pb.ObjUrl.URL();
            input.readMessage(value);
            addUrls(value);
            break;
          }
          case 50: {
            com.baidu.im.frame.pb.ObjData.Data value = new com.baidu.im.frame.pb.ObjData.Data();
            input.readMessage(value);
            addDatas(value);
            break;
          }
          case 58: {
            addExtContent(input.readBytes());
            break;
          }
        }
      }
    }

    public static MsgContent parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (MsgContent) (new MsgContent().mergeFrom(data));
    }

    public static MsgContent parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new MsgContent().mergeFrom(input);
    }

  }

}
