// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class ObjMsgPushResult {
  private ObjMsgPushResult() {}
  @SuppressWarnings("hiding")
  public static final class MsgPushResult extends
      com.google.protobuf.micro.MessageMicro {
    public MsgPushResult() {}

    // required .EChatType chatType = 1;
    public static final int CHATTYPE_FIELD_NUMBER = 1;
    private boolean hasChatType;
    private int chatType_ = com.baidu.im.frame.pb.EnumChatType.CHAT_P2P;
    public boolean hasChatType() { return hasChatType; }
    public int getChatType() { return chatType_; }
    public MsgPushResult setChatType(int value) {
      hasChatType = true;
      chatType_ = value;
      return this;
    }
    public MsgPushResult clearChatType() {
      hasChatType = false;
      chatType_ = com.baidu.im.frame.pb.EnumChatType.CHAT_P2P;
      return this;
    }

    // optional string toId = 2;
    public static final int TOID_FIELD_NUMBER = 2;
    private boolean hasToId;
    private java.lang.String toId_ = "";
    public java.lang.String getToId() { return toId_; }
    public boolean hasToId() { return hasToId; }
    public MsgPushResult setToId(java.lang.String value) {
      hasToId = true;
      toId_ = value;
      return this;
    }
    public MsgPushResult clearToId() {
      hasToId = false;
      toId_ = "";
      return this;
    }

    // optional .EPlatformType platformType = 3;
    public static final int PLATFORMTYPE_FIELD_NUMBER = 3;
    private boolean hasPlatformType;
    private int platformType_ = com.baidu.im.frame.pb.EnumPlatformType.WINDOWS;
    public boolean hasPlatformType() { return hasPlatformType; }
    public int getPlatformType() { return platformType_; }
    public MsgPushResult setPlatformType(int value) {
      hasPlatformType = true;
      platformType_ = value;
      return this;
    }
    public MsgPushResult clearPlatformType() {
      hasPlatformType = false;
      platformType_ = com.baidu.im.frame.pb.EnumPlatformType.WINDOWS;
      return this;
    }

    // required uint64 seq = 4;
    public static final int SEQ_FIELD_NUMBER = 4;
    private boolean hasSeq;
    private long seq_ = 0L;
    public long getSeq() { return seq_; }
    public boolean hasSeq() { return hasSeq; }
    public MsgPushResult setSeq(long value) {
      hasSeq = true;
      seq_ = value;
      return this;
    }
    public MsgPushResult clearSeq() {
      hasSeq = false;
      seq_ = 0L;
      return this;
    }

    // required bool submitSuccess = 5;
    public static final int SUBMITSUCCESS_FIELD_NUMBER = 5;
    private boolean hasSubmitSuccess;
    private boolean submitSuccess_ = false;
    public boolean getSubmitSuccess() { return submitSuccess_; }
    public boolean hasSubmitSuccess() { return hasSubmitSuccess; }
    public MsgPushResult setSubmitSuccess(boolean value) {
      hasSubmitSuccess = true;
      submitSuccess_ = value;
      return this;
    }
    public MsgPushResult clearSubmitSuccess() {
      hasSubmitSuccess = false;
      submitSuccess_ = false;
      return this;
    }

    // optional bool msgReceived = 6;
    public static final int MSGRECEIVED_FIELD_NUMBER = 6;
    private boolean hasMsgReceived;
    private boolean msgReceived_ = false;
    public boolean getMsgReceived() { return msgReceived_; }
    public boolean hasMsgReceived() { return hasMsgReceived; }
    public MsgPushResult setMsgReceived(boolean value) {
      hasMsgReceived = true;
      msgReceived_ = value;
      return this;
    }
    public MsgPushResult clearMsgReceived() {
      hasMsgReceived = false;
      msgReceived_ = false;
      return this;
    }

    // optional bool notifyReceived = 7;
    public static final int NOTIFYRECEIVED_FIELD_NUMBER = 7;
    private boolean hasNotifyReceived;
    private boolean notifyReceived_ = false;
    public boolean getNotifyReceived() { return notifyReceived_; }
    public boolean hasNotifyReceived() { return hasNotifyReceived; }
    public MsgPushResult setNotifyReceived(boolean value) {
      hasNotifyReceived = true;
      notifyReceived_ = value;
      return this;
    }
    public MsgPushResult clearNotifyReceived() {
      hasNotifyReceived = false;
      notifyReceived_ = false;
      return this;
    }

    public final MsgPushResult clear() {
      clearChatType();
      clearToId();
      clearPlatformType();
      clearSeq();
      clearSubmitSuccess();
      clearMsgReceived();
      clearNotifyReceived();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasChatType) return false;
      if (!hasSeq) return false;
      if (!hasSubmitSuccess) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasChatType()) {
        output.writeInt32(1, getChatType());
      }
      if (hasToId()) {
        output.writeString(2, getToId());
      }
      if (hasPlatformType()) {
        output.writeInt32(3, getPlatformType());
      }
      if (hasSeq()) {
        output.writeUInt64(4, getSeq());
      }
      if (hasSubmitSuccess()) {
        output.writeBool(5, getSubmitSuccess());
      }
      if (hasMsgReceived()) {
        output.writeBool(6, getMsgReceived());
      }
      if (hasNotifyReceived()) {
        output.writeBool(7, getNotifyReceived());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasChatType()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeInt32Size(1, getChatType());
      }
      if (hasToId()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(2, getToId());
      }
      if (hasPlatformType()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeInt32Size(3, getPlatformType());
      }
      if (hasSeq()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt64Size(4, getSeq());
      }
      if (hasSubmitSuccess()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeBoolSize(5, getSubmitSuccess());
      }
      if (hasMsgReceived()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeBoolSize(6, getMsgReceived());
      }
      if (hasNotifyReceived()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeBoolSize(7, getNotifyReceived());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public MsgPushResult mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
              setChatType(input.readInt32());
            break;
          }
          case 18: {
            setToId(input.readString());
            break;
          }
          case 24: {
              setPlatformType(input.readInt32());
            break;
          }
          case 32: {
            setSeq(input.readUInt64());
            break;
          }
          case 40: {
            setSubmitSuccess(input.readBool());
            break;
          }
          case 48: {
            setMsgReceived(input.readBool());
            break;
          }
          case 56: {
            setNotifyReceived(input.readBool());
            break;
          }
        }
      }
    }

    public static MsgPushResult parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (MsgPushResult) (new MsgPushResult().mergeFrom(data));
    }

    public static MsgPushResult parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new MsgPushResult().mergeFrom(input);
    }

  }

}
