// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class ObjPushData {
  private ObjPushData() {}
  @SuppressWarnings("hiding")
  public static final class PushData extends
      com.google.protobuf.micro.MessageMicro {
    public PushData() {}

    // required .EMessageType messageType = 1;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private boolean hasMessageType;
    private int messageType_ = com.baidu.im.frame.pb.EnumMessageType.NORMAL_MSG;
    public boolean hasMessageType() { return hasMessageType; }
    public int getMessageType() { return messageType_; }
    public PushData setMessageType(int value) {
      hasMessageType = true;
      messageType_ = value;
      return this;
    }
    public PushData clearMessageType() {
      hasMessageType = false;
      messageType_ = com.baidu.im.frame.pb.EnumMessageType.NORMAL_MSG;
      return this;
    }

    // optional .NormalMessage normalMessage = 2;
    public static final int NORMALMESSAGE_FIELD_NUMBER = 2;
    private boolean hasNormalMessage;
    private com.baidu.im.frame.pb.ObjNormalMessage.NormalMessage normalMessage_ = null;
    public boolean hasNormalMessage() { return hasNormalMessage; }
    public com.baidu.im.frame.pb.ObjNormalMessage.NormalMessage getNormalMessage() { return normalMessage_; }
    public PushData setNormalMessage(com.baidu.im.frame.pb.ObjNormalMessage.NormalMessage value) {
      if (value == null) {
        throw new NullPointerException();
      }
      hasNormalMessage = true;
      normalMessage_ = value;
      return this;
    }
    public PushData clearNormalMessage() {
      hasNormalMessage = false;
      normalMessage_ = null;
      return this;
    }

    // optional .NotifyMessage sysNotifyMessage = 3;
    public static final int SYSNOTIFYMESSAGE_FIELD_NUMBER = 3;
    private boolean hasSysNotifyMessage;
    private com.baidu.im.frame.pb.ObjNotifyMessage.NotifyMessage sysNotifyMessage_ = null;
    public boolean hasSysNotifyMessage() { return hasSysNotifyMessage; }
    public com.baidu.im.frame.pb.ObjNotifyMessage.NotifyMessage getSysNotifyMessage() { return sysNotifyMessage_; }
    public PushData setSysNotifyMessage(com.baidu.im.frame.pb.ObjNotifyMessage.NotifyMessage value) {
      if (value == null) {
        throw new NullPointerException();
      }
      hasSysNotifyMessage = true;
      sysNotifyMessage_ = value;
      return this;
    }
    public PushData clearSysNotifyMessage() {
      hasSysNotifyMessage = false;
      sysNotifyMessage_ = null;
      return this;
    }

    public final PushData clear() {
      clearMessageType();
      clearNormalMessage();
      clearSysNotifyMessage();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasMessageType) return false;
      if (hasNormalMessage()) {
        if (!getNormalMessage().isInitialized()) return false;
      }
      if (hasSysNotifyMessage()) {
        if (!getSysNotifyMessage().isInitialized()) return false;
      }
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasMessageType()) {
        output.writeInt32(1, getMessageType());
      }
      if (hasNormalMessage()) {
        output.writeMessage(2, getNormalMessage());
      }
      if (hasSysNotifyMessage()) {
        output.writeMessage(3, getSysNotifyMessage());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasMessageType()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeInt32Size(1, getMessageType());
      }
      if (hasNormalMessage()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(2, getNormalMessage());
      }
      if (hasSysNotifyMessage()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(3, getSysNotifyMessage());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public PushData mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
              setMessageType(input.readInt32());
            break;
          }
          case 18: {
            com.baidu.im.frame.pb.ObjNormalMessage.NormalMessage value = new com.baidu.im.frame.pb.ObjNormalMessage.NormalMessage();
            input.readMessage(value);
            setNormalMessage(value);
            break;
          }
          case 26: {
            com.baidu.im.frame.pb.ObjNotifyMessage.NotifyMessage value = new com.baidu.im.frame.pb.ObjNotifyMessage.NotifyMessage();
            input.readMessage(value);
            setSysNotifyMessage(value);
            break;
          }
        }
      }
    }

    public static PushData parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (PushData) (new PushData().mergeFrom(data));
    }

    public static PushData parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new PushData().mergeFrom(input);
    }

  }

}
