// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class ObjSplitPartInfo {
  private ObjSplitPartInfo() {}
  @SuppressWarnings("hiding")
  public static final class SplitPartInfo extends
      com.google.protobuf.micro.MessageMicro {
    public SplitPartInfo() {}

    // required uint32 partNumber = 1;
    public static final int PARTNUMBER_FIELD_NUMBER = 1;
    private boolean hasPartNumber;
    private int partNumber_ = 0;
    public int getPartNumber() { return partNumber_; }
    public boolean hasPartNumber() { return hasPartNumber; }
    public SplitPartInfo setPartNumber(int value) {
      hasPartNumber = true;
      partNumber_ = value;
      return this;
    }
    public SplitPartInfo clearPartNumber() {
      hasPartNumber = false;
      partNumber_ = 0;
      return this;
    }

    // optional string md5 = 2;
    public static final int MD5_FIELD_NUMBER = 2;
    private boolean hasMd5;
    private java.lang.String md5_ = "";
    public java.lang.String getMd5() { return md5_; }
    public boolean hasMd5() { return hasMd5; }
    public SplitPartInfo setMd5(java.lang.String value) {
      hasMd5 = true;
      md5_ = value;
      return this;
    }
    public SplitPartInfo clearMd5() {
      hasMd5 = false;
      md5_ = "";
      return this;
    }

    public final SplitPartInfo clear() {
      clearPartNumber();
      clearMd5();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasPartNumber) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasPartNumber()) {
        output.writeUInt32(1, getPartNumber());
      }
      if (hasMd5()) {
        output.writeString(2, getMd5());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasPartNumber()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt32Size(1, getPartNumber());
      }
      if (hasMd5()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(2, getMd5());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public SplitPartInfo mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            setPartNumber(input.readUInt32());
            break;
          }
          case 18: {
            setMd5(input.readString());
            break;
          }
        }
      }
    }

    public static SplitPartInfo parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (SplitPartInfo) (new SplitPartInfo().mergeFrom(data));
    }

    public static SplitPartInfo parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new SplitPartInfo().mergeFrom(input);
    }

  }

}
