// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class ObjText {
  private ObjText() {}
  @SuppressWarnings("hiding")
  public static final class Text extends
      com.google.protobuf.micro.MessageMicro {
    public Text() {}

    // required string textId = 1;
    public static final int TEXTID_FIELD_NUMBER = 1;
    private boolean hasTextId;
    private java.lang.String textId_ = "";
    public java.lang.String getTextId() { return textId_; }
    public boolean hasTextId() { return hasTextId; }
    public Text setTextId(java.lang.String value) {
      hasTextId = true;
      textId_ = value;
      return this;
    }
    public Text clearTextId() {
      hasTextId = false;
      textId_ = "";
      return this;
    }

    // required string content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private boolean hasContent;
    private java.lang.String content_ = "";
    public java.lang.String getContent() { return content_; }
    public boolean hasContent() { return hasContent; }
    public Text setContent(java.lang.String value) {
      hasContent = true;
      content_ = value;
      return this;
    }
    public Text clearContent() {
      hasContent = false;
      content_ = "";
      return this;
    }

    // optional string title = 3;
    public static final int TITLE_FIELD_NUMBER = 3;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public java.lang.String getTitle() { return title_; }
    public boolean hasTitle() { return hasTitle; }
    public Text setTitle(java.lang.String value) {
      hasTitle = true;
      title_ = value;
      return this;
    }
    public Text clearTitle() {
      hasTitle = false;
      title_ = "";
      return this;
    }

    // optional string description = 4;
    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private boolean hasDescription;
    private java.lang.String description_ = "";
    public java.lang.String getDescription() { return description_; }
    public boolean hasDescription() { return hasDescription; }
    public Text setDescription(java.lang.String value) {
      hasDescription = true;
      description_ = value;
      return this;
    }
    public Text clearDescription() {
      hasDescription = false;
      description_ = "";
      return this;
    }

    // optional string extInfo = 5;
    public static final int EXTINFO_FIELD_NUMBER = 5;
    private boolean hasExtInfo;
    private java.lang.String extInfo_ = "";
    public java.lang.String getExtInfo() { return extInfo_; }
    public boolean hasExtInfo() { return hasExtInfo; }
    public Text setExtInfo(java.lang.String value) {
      hasExtInfo = true;
      extInfo_ = value;
      return this;
    }
    public Text clearExtInfo() {
      hasExtInfo = false;
      extInfo_ = "";
      return this;
    }

    public final Text clear() {
      clearTextId();
      clearContent();
      clearTitle();
      clearDescription();
      clearExtInfo();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasTextId) return false;
      if (!hasContent) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasTextId()) {
        output.writeString(1, getTextId());
      }
      if (hasContent()) {
        output.writeString(2, getContent());
      }
      if (hasTitle()) {
        output.writeString(3, getTitle());
      }
      if (hasDescription()) {
        output.writeString(4, getDescription());
      }
      if (hasExtInfo()) {
        output.writeString(5, getExtInfo());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasTextId()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(1, getTextId());
      }
      if (hasContent()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(2, getContent());
      }
      if (hasTitle()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(3, getTitle());
      }
      if (hasDescription()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(4, getDescription());
      }
      if (hasExtInfo()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(5, getExtInfo());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public Text mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            setTextId(input.readString());
            break;
          }
          case 18: {
            setContent(input.readString());
            break;
          }
          case 26: {
            setTitle(input.readString());
            break;
          }
          case 34: {
            setDescription(input.readString());
            break;
          }
          case 42: {
            setExtInfo(input.readString());
            break;
          }
        }
      }
    }

    public static Text parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (Text) (new Text().mergeFrom(data));
    }

    public static Text parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new Text().mergeFrom(input);
    }

  }

}
