// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class ObjUrl {
  private ObjUrl() {}
  @SuppressWarnings("hiding")
  public static final class URL extends
      com.google.protobuf.micro.MessageMicro {
    public URL() {}

    // required string urlId = 1;
    public static final int URLID_FIELD_NUMBER = 1;
    private boolean hasUrlId;
    private java.lang.String urlId_ = "";
    public java.lang.String getUrlId() { return urlId_; }
    public boolean hasUrlId() { return hasUrlId; }
    public URL setUrlId(java.lang.String value) {
      hasUrlId = true;
      urlId_ = value;
      return this;
    }
    public URL clearUrlId() {
      hasUrlId = false;
      urlId_ = "";
      return this;
    }

    // required string url = 2;
    public static final int URL_FIELD_NUMBER = 2;
    private boolean hasUrl;
    private java.lang.String url_ = "";
    public java.lang.String getUrl() { return url_; }
    public boolean hasUrl() { return hasUrl; }
    public URL setUrl(java.lang.String value) {
      hasUrl = true;
      url_ = value;
      return this;
    }
    public URL clearUrl() {
      hasUrl = false;
      url_ = "";
      return this;
    }

    // optional string title = 3;
    public static final int TITLE_FIELD_NUMBER = 3;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public java.lang.String getTitle() { return title_; }
    public boolean hasTitle() { return hasTitle; }
    public URL setTitle(java.lang.String value) {
      hasTitle = true;
      title_ = value;
      return this;
    }
    public URL clearTitle() {
      hasTitle = false;
      title_ = "";
      return this;
    }

    // optional string extInfo = 4;
    public static final int EXTINFO_FIELD_NUMBER = 4;
    private boolean hasExtInfo;
    private java.lang.String extInfo_ = "";
    public java.lang.String getExtInfo() { return extInfo_; }
    public boolean hasExtInfo() { return hasExtInfo; }
    public URL setExtInfo(java.lang.String value) {
      hasExtInfo = true;
      extInfo_ = value;
      return this;
    }
    public URL clearExtInfo() {
      hasExtInfo = false;
      extInfo_ = "";
      return this;
    }

    public final URL clear() {
      clearUrlId();
      clearUrl();
      clearTitle();
      clearExtInfo();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasUrlId) return false;
      if (!hasUrl) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasUrlId()) {
        output.writeString(1, getUrlId());
      }
      if (hasUrl()) {
        output.writeString(2, getUrl());
      }
      if (hasTitle()) {
        output.writeString(3, getTitle());
      }
      if (hasExtInfo()) {
        output.writeString(4, getExtInfo());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasUrlId()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(1, getUrlId());
      }
      if (hasUrl()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(2, getUrl());
      }
      if (hasTitle()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(3, getTitle());
      }
      if (hasExtInfo()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(4, getExtInfo());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public URL mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            setUrlId(input.readString());
            break;
          }
          case 18: {
            setUrl(input.readString());
            break;
          }
          case 26: {
            setTitle(input.readString());
            break;
          }
          case 34: {
            setExtInfo(input.readString());
            break;
          }
        }
      }
    }

    public static URL parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (URL) (new URL().mergeFrom(data));
    }

    public static URL parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new URL().mergeFrom(input);
    }

  }

}
