// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class ObjVoice {
  private ObjVoice() {}
  @SuppressWarnings("hiding")
  public static final class Voice extends
      com.google.protobuf.micro.MessageMicro {
    public Voice() {}

    // optional string voiceId = 1;
    public static final int VOICEID_FIELD_NUMBER = 1;
    private boolean hasVoiceId;
    private java.lang.String voiceId_ = "";
    public java.lang.String getVoiceId() { return voiceId_; }
    public boolean hasVoiceId() { return hasVoiceId; }
    public Voice setVoiceId(java.lang.String value) {
      hasVoiceId = true;
      voiceId_ = value;
      return this;
    }
    public Voice clearVoiceId() {
      hasVoiceId = false;
      voiceId_ = "";
      return this;
    }

    // required string md5 = 2;
    public static final int MD5_FIELD_NUMBER = 2;
    private boolean hasMd5;
    private java.lang.String md5_ = "";
    public java.lang.String getMd5() { return md5_; }
    public boolean hasMd5() { return hasMd5; }
    public Voice setMd5(java.lang.String value) {
      hasMd5 = true;
      md5_ = value;
      return this;
    }
    public Voice clearMd5() {
      hasMd5 = false;
      md5_ = "";
      return this;
    }

    // required uint32 size = 3;
    public static final int SIZE_FIELD_NUMBER = 3;
    private boolean hasSize;
    private int size_ = 0;
    public int getSize() { return size_; }
    public boolean hasSize() { return hasSize; }
    public Voice setSize(int value) {
      hasSize = true;
      size_ = value;
      return this;
    }
    public Voice clearSize() {
      hasSize = false;
      size_ = 0;
      return this;
    }

    // optional uint32 timeLen = 4;
    public static final int TIMELEN_FIELD_NUMBER = 4;
    private boolean hasTimeLen;
    private int timeLen_ = 0;
    public int getTimeLen() { return timeLen_; }
    public boolean hasTimeLen() { return hasTimeLen; }
    public Voice setTimeLen(int value) {
      hasTimeLen = true;
      timeLen_ = value;
      return this;
    }
    public Voice clearTimeLen() {
      hasTimeLen = false;
      timeLen_ = 0;
      return this;
    }

    // optional string url = 5;
    public static final int URL_FIELD_NUMBER = 5;
    private boolean hasUrl;
    private java.lang.String url_ = "";
    public java.lang.String getUrl() { return url_; }
    public boolean hasUrl() { return hasUrl; }
    public Voice setUrl(java.lang.String value) {
      hasUrl = true;
      url_ = value;
      return this;
    }
    public Voice clearUrl() {
      hasUrl = false;
      url_ = "";
      return this;
    }

    // optional string extInfo = 6;
    public static final int EXTINFO_FIELD_NUMBER = 6;
    private boolean hasExtInfo;
    private java.lang.String extInfo_ = "";
    public java.lang.String getExtInfo() { return extInfo_; }
    public boolean hasExtInfo() { return hasExtInfo; }
    public Voice setExtInfo(java.lang.String value) {
      hasExtInfo = true;
      extInfo_ = value;
      return this;
    }
    public Voice clearExtInfo() {
      hasExtInfo = false;
      extInfo_ = "";
      return this;
    }

    public final Voice clear() {
      clearVoiceId();
      clearMd5();
      clearSize();
      clearTimeLen();
      clearUrl();
      clearExtInfo();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasMd5) return false;
      if (!hasSize) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasVoiceId()) {
        output.writeString(1, getVoiceId());
      }
      if (hasMd5()) {
        output.writeString(2, getMd5());
      }
      if (hasSize()) {
        output.writeUInt32(3, getSize());
      }
      if (hasTimeLen()) {
        output.writeUInt32(4, getTimeLen());
      }
      if (hasUrl()) {
        output.writeString(5, getUrl());
      }
      if (hasExtInfo()) {
        output.writeString(6, getExtInfo());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasVoiceId()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(1, getVoiceId());
      }
      if (hasMd5()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(2, getMd5());
      }
      if (hasSize()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt32Size(3, getSize());
      }
      if (hasTimeLen()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt32Size(4, getTimeLen());
      }
      if (hasUrl()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(5, getUrl());
      }
      if (hasExtInfo()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(6, getExtInfo());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public Voice mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            setVoiceId(input.readString());
            break;
          }
          case 18: {
            setMd5(input.readString());
            break;
          }
          case 24: {
            setSize(input.readUInt32());
            break;
          }
          case 32: {
            setTimeLen(input.readUInt32());
            break;
          }
          case 42: {
            setUrl(input.readString());
            break;
          }
          case 50: {
            setExtInfo(input.readString());
            break;
          }
        }
      }
    }

    public static Voice parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (Voice) (new Voice().mergeFrom(data));
    }

    public static Voice parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new Voice().mergeFrom(input);
    }

  }

}
