// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class ProGetSplitPartsSign {
  private ProGetSplitPartsSign() {}
  @SuppressWarnings("hiding")
  public static final class GetSplitPartsSignReq extends
      com.google.protobuf.micro.MessageMicro {
    public GetSplitPartsSignReq() {}

    // required string fileId = 1;
    public static final int FILEID_FIELD_NUMBER = 1;
    private boolean hasFileId;
    private java.lang.String fileId_ = "";
    public java.lang.String getFileId() { return fileId_; }
    public boolean hasFileId() { return hasFileId; }
    public GetSplitPartsSignReq setFileId(java.lang.String value) {
      hasFileId = true;
      fileId_ = value;
      return this;
    }
    public GetSplitPartsSignReq clearFileId() {
      hasFileId = false;
      fileId_ = "";
      return this;
    }

    // optional string bossHost = 2;
    public static final int BOSSHOST_FIELD_NUMBER = 2;
    private boolean hasBossHost;
    private java.lang.String bossHost_ = "";
    public java.lang.String getBossHost() { return bossHost_; }
    public boolean hasBossHost() { return hasBossHost; }
    public GetSplitPartsSignReq setBossHost(java.lang.String value) {
      hasBossHost = true;
      bossHost_ = value;
      return this;
    }
    public GetSplitPartsSignReq clearBossHost() {
      hasBossHost = false;
      bossHost_ = "";
      return this;
    }

    // required string uploadId = 3;
    public static final int UPLOADID_FIELD_NUMBER = 3;
    private boolean hasUploadId;
    private java.lang.String uploadId_ = "";
    public java.lang.String getUploadId() { return uploadId_; }
    public boolean hasUploadId() { return hasUploadId; }
    public GetSplitPartsSignReq setUploadId(java.lang.String value) {
      hasUploadId = true;
      uploadId_ = value;
      return this;
    }
    public GetSplitPartsSignReq clearUploadId() {
      hasUploadId = false;
      uploadId_ = "";
      return this;
    }

    // repeated .SplitPartInfo parts = 4;
    public static final int PARTS_FIELD_NUMBER = 4;
    private java.util.List<com.baidu.im.frame.pb.ObjSplitPartInfo.SplitPartInfo> parts_ =
      java.util.Collections.emptyList();
    public java.util.List<com.baidu.im.frame.pb.ObjSplitPartInfo.SplitPartInfo> getPartsList() {
      return parts_;
    }
    public int getPartsCount() { return parts_.size(); }
    public com.baidu.im.frame.pb.ObjSplitPartInfo.SplitPartInfo getParts(int index) {
      return parts_.get(index);
    }
    public GetSplitPartsSignReq setParts(int index, com.baidu.im.frame.pb.ObjSplitPartInfo.SplitPartInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      parts_.set(index, value);
      return this;
    }
    public GetSplitPartsSignReq addParts(com.baidu.im.frame.pb.ObjSplitPartInfo.SplitPartInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (parts_.isEmpty()) {
        parts_ = new java.util.ArrayList<com.baidu.im.frame.pb.ObjSplitPartInfo.SplitPartInfo>();
      }
      parts_.add(value);
      return this;
    }
    public GetSplitPartsSignReq clearParts() {
      parts_ = java.util.Collections.emptyList();
      return this;
    }

    public final GetSplitPartsSignReq clear() {
      clearFileId();
      clearBossHost();
      clearUploadId();
      clearParts();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasFileId) return false;
      if (!hasUploadId) return false;
      for (com.baidu.im.frame.pb.ObjSplitPartInfo.SplitPartInfo element : getPartsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasFileId()) {
        output.writeString(1, getFileId());
      }
      if (hasBossHost()) {
        output.writeString(2, getBossHost());
      }
      if (hasUploadId()) {
        output.writeString(3, getUploadId());
      }
      for (com.baidu.im.frame.pb.ObjSplitPartInfo.SplitPartInfo element : getPartsList()) {
        output.writeMessage(4, element);
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasFileId()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(1, getFileId());
      }
      if (hasBossHost()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(2, getBossHost());
      }
      if (hasUploadId()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(3, getUploadId());
      }
      for (com.baidu.im.frame.pb.ObjSplitPartInfo.SplitPartInfo element : getPartsList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(4, element);
      }
      cachedSize = size;
      return size;
    }

    @Override
    public GetSplitPartsSignReq mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            setFileId(input.readString());
            break;
          }
          case 18: {
            setBossHost(input.readString());
            break;
          }
          case 26: {
            setUploadId(input.readString());
            break;
          }
          case 34: {
            com.baidu.im.frame.pb.ObjSplitPartInfo.SplitPartInfo value = new com.baidu.im.frame.pb.ObjSplitPartInfo.SplitPartInfo();
            input.readMessage(value);
            addParts(value);
            break;
          }
        }
      }
    }

    public static GetSplitPartsSignReq parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (GetSplitPartsSignReq) (new GetSplitPartsSignReq().mergeFrom(data));
    }

    public static GetSplitPartsSignReq parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new GetSplitPartsSignReq().mergeFrom(input);
    }

  }

  @SuppressWarnings("hiding")
  public static final class GetSplitPartsSignRsp extends
      com.google.protobuf.micro.MessageMicro {
    public GetSplitPartsSignRsp() {}

    // repeated .SplitPartSign partSigns = 1;
    public static final int PARTSIGNS_FIELD_NUMBER = 1;
    private java.util.List<com.baidu.im.frame.pb.ObjSplitPartSign.SplitPartSign> partSigns_ =
      java.util.Collections.emptyList();
    public java.util.List<com.baidu.im.frame.pb.ObjSplitPartSign.SplitPartSign> getPartSignsList() {
      return partSigns_;
    }
    public int getPartSignsCount() { return partSigns_.size(); }
    public com.baidu.im.frame.pb.ObjSplitPartSign.SplitPartSign getPartSigns(int index) {
      return partSigns_.get(index);
    }
    public GetSplitPartsSignRsp setPartSigns(int index, com.baidu.im.frame.pb.ObjSplitPartSign.SplitPartSign value) {
      if (value == null) {
        throw new NullPointerException();
      }
      partSigns_.set(index, value);
      return this;
    }
    public GetSplitPartsSignRsp addPartSigns(com.baidu.im.frame.pb.ObjSplitPartSign.SplitPartSign value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (partSigns_.isEmpty()) {
        partSigns_ = new java.util.ArrayList<com.baidu.im.frame.pb.ObjSplitPartSign.SplitPartSign>();
      }
      partSigns_.add(value);
      return this;
    }
    public GetSplitPartsSignRsp clearPartSigns() {
      partSigns_ = java.util.Collections.emptyList();
      return this;
    }

    public final GetSplitPartsSignRsp clear() {
      clearPartSigns();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      for (com.baidu.im.frame.pb.ObjSplitPartSign.SplitPartSign element : getPartSignsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      for (com.baidu.im.frame.pb.ObjSplitPartSign.SplitPartSign element : getPartSignsList()) {
        output.writeMessage(1, element);
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      for (com.baidu.im.frame.pb.ObjSplitPartSign.SplitPartSign element : getPartSignsList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(1, element);
      }
      cachedSize = size;
      return size;
    }

    @Override
    public GetSplitPartsSignRsp mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            com.baidu.im.frame.pb.ObjSplitPartSign.SplitPartSign value = new com.baidu.im.frame.pb.ObjSplitPartSign.SplitPartSign();
            input.readMessage(value);
            addPartSigns(value);
            break;
          }
        }
      }
    }

    public static GetSplitPartsSignRsp parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (GetSplitPartsSignRsp) (new GetSplitPartsSignRsp().mergeFrom(data));
    }

    public static GetSplitPartsSignRsp parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new GetSplitPartsSignRsp().mergeFrom(input);
    }

  }

}
