// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.im.frame.pb;

public final class ProGetDownloadSign {
  private ProGetDownloadSign() {}
  @SuppressWarnings("hiding")
  public static final class GetDownloadSignReqItem extends
      com.google.protobuf.micro.MessageMicro {
    public GetDownloadSignReqItem() {}

    // required string fileId = 1;
    public static final int FILEID_FIELD_NUMBER = 1;
    private boolean hasFileId;
    private java.lang.String fileId_ = "";
    public java.lang.String getFileId() { return fileId_; }
    public boolean hasFileId() { return hasFileId; }
    public GetDownloadSignReqItem setFileId(java.lang.String value) {
      hasFileId = true;
      fileId_ = value;
      return this;
    }
    public GetDownloadSignReqItem clearFileId() {
      hasFileId = false;
      fileId_ = "";
      return this;
    }

    // optional string bossHost = 2;
    public static final int BOSSHOST_FIELD_NUMBER = 2;
    private boolean hasBossHost;
    private java.lang.String bossHost_ = "";
    public java.lang.String getBossHost() { return bossHost_; }
    public boolean hasBossHost() { return hasBossHost; }
    public GetDownloadSignReqItem setBossHost(java.lang.String value) {
      hasBossHost = true;
      bossHost_ = value;
      return this;
    }
    public GetDownloadSignReqItem clearBossHost() {
      hasBossHost = false;
      bossHost_ = "";
      return this;
    }

    // required string md5 = 3;
    public static final int MD5_FIELD_NUMBER = 3;
    private boolean hasMd5;
    private java.lang.String md5_ = "";
    public java.lang.String getMd5() { return md5_; }
    public boolean hasMd5() { return hasMd5; }
    public GetDownloadSignReqItem setMd5(java.lang.String value) {
      hasMd5 = true;
      md5_ = value;
      return this;
    }
    public GetDownloadSignReqItem clearMd5() {
      hasMd5 = false;
      md5_ = "";
      return this;
    }

    public final GetDownloadSignReqItem clear() {
      clearFileId();
      clearBossHost();
      clearMd5();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasFileId) return false;
      if (!hasMd5) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasFileId()) {
        output.writeString(1, getFileId());
      }
      if (hasBossHost()) {
        output.writeString(2, getBossHost());
      }
      if (hasMd5()) {
        output.writeString(3, getMd5());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasFileId()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(1, getFileId());
      }
      if (hasBossHost()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(2, getBossHost());
      }
      if (hasMd5()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(3, getMd5());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public GetDownloadSignReqItem mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            setFileId(input.readString());
            break;
          }
          case 18: {
            setBossHost(input.readString());
            break;
          }
          case 26: {
            setMd5(input.readString());
            break;
          }
        }
      }
    }

    public static GetDownloadSignReqItem parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (GetDownloadSignReqItem) (new GetDownloadSignReqItem().mergeFrom(data));
    }

    public static GetDownloadSignReqItem parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new GetDownloadSignReqItem().mergeFrom(input);
    }

  }

  @SuppressWarnings("hiding")
  public static final class GetDownloadSignRspItem extends
      com.google.protobuf.micro.MessageMicro {
    public GetDownloadSignRspItem() {}

    // required string fileId = 1;
    public static final int FILEID_FIELD_NUMBER = 1;
    private boolean hasFileId;
    private java.lang.String fileId_ = "";
    public java.lang.String getFileId() { return fileId_; }
    public boolean hasFileId() { return hasFileId; }
    public GetDownloadSignRspItem setFileId(java.lang.String value) {
      hasFileId = true;
      fileId_ = value;
      return this;
    }
    public GetDownloadSignRspItem clearFileId() {
      hasFileId = false;
      fileId_ = "";
      return this;
    }

    // required string sign = 2;
    public static final int SIGN_FIELD_NUMBER = 2;
    private boolean hasSign;
    private java.lang.String sign_ = "";
    public java.lang.String getSign() { return sign_; }
    public boolean hasSign() { return hasSign; }
    public GetDownloadSignRspItem setSign(java.lang.String value) {
      hasSign = true;
      sign_ = value;
      return this;
    }
    public GetDownloadSignRspItem clearSign() {
      hasSign = false;
      sign_ = "";
      return this;
    }

    // required string downloadUrl = 3;
    public static final int DOWNLOADURL_FIELD_NUMBER = 3;
    private boolean hasDownloadUrl;
    private java.lang.String downloadUrl_ = "";
    public java.lang.String getDownloadUrl() { return downloadUrl_; }
    public boolean hasDownloadUrl() { return hasDownloadUrl; }
    public GetDownloadSignRspItem setDownloadUrl(java.lang.String value) {
      hasDownloadUrl = true;
      downloadUrl_ = value;
      return this;
    }
    public GetDownloadSignRspItem clearDownloadUrl() {
      hasDownloadUrl = false;
      downloadUrl_ = "";
      return this;
    }

    public final GetDownloadSignRspItem clear() {
      clearFileId();
      clearSign();
      clearDownloadUrl();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasFileId) return false;
      if (!hasSign) return false;
      if (!hasDownloadUrl) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasFileId()) {
        output.writeString(1, getFileId());
      }
      if (hasSign()) {
        output.writeString(2, getSign());
      }
      if (hasDownloadUrl()) {
        output.writeString(3, getDownloadUrl());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasFileId()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(1, getFileId());
      }
      if (hasSign()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(2, getSign());
      }
      if (hasDownloadUrl()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(3, getDownloadUrl());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public GetDownloadSignRspItem mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            setFileId(input.readString());
            break;
          }
          case 18: {
            setSign(input.readString());
            break;
          }
          case 26: {
            setDownloadUrl(input.readString());
            break;
          }
        }
      }
    }

    public static GetDownloadSignRspItem parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (GetDownloadSignRspItem) (new GetDownloadSignRspItem().mergeFrom(data));
    }

    public static GetDownloadSignRspItem parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new GetDownloadSignRspItem().mergeFrom(input);
    }

  }

  @SuppressWarnings("hiding")
  public static final class GetDownloadSignReq extends
      com.google.protobuf.micro.MessageMicro {
    public GetDownloadSignReq() {}

    // repeated .GetDownloadSignReqItem reqList = 1;
    public static final int REQLIST_FIELD_NUMBER = 1;
    private java.util.List<com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignReqItem> reqList_ =
      java.util.Collections.emptyList();
    public java.util.List<com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignReqItem> getReqListList() {
      return reqList_;
    }
    public int getReqListCount() { return reqList_.size(); }
    public com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignReqItem getReqList(int index) {
      return reqList_.get(index);
    }
    public GetDownloadSignReq setReqList(int index, com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignReqItem value) {
      if (value == null) {
        throw new NullPointerException();
      }
      reqList_.set(index, value);
      return this;
    }
    public GetDownloadSignReq addReqList(com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignReqItem value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (reqList_.isEmpty()) {
        reqList_ = new java.util.ArrayList<com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignReqItem>();
      }
      reqList_.add(value);
      return this;
    }
    public GetDownloadSignReq clearReqList() {
      reqList_ = java.util.Collections.emptyList();
      return this;
    }

    public final GetDownloadSignReq clear() {
      clearReqList();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      for (com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignReqItem element : getReqListList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      for (com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignReqItem element : getReqListList()) {
        output.writeMessage(1, element);
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      for (com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignReqItem element : getReqListList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(1, element);
      }
      cachedSize = size;
      return size;
    }

    @Override
    public GetDownloadSignReq mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignReqItem value = new com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignReqItem();
            input.readMessage(value);
            addReqList(value);
            break;
          }
        }
      }
    }

    public static GetDownloadSignReq parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (GetDownloadSignReq) (new GetDownloadSignReq().mergeFrom(data));
    }

    public static GetDownloadSignReq parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new GetDownloadSignReq().mergeFrom(input);
    }

  }

  @SuppressWarnings("hiding")
  public static final class GetDownloadSignRsp extends
      com.google.protobuf.micro.MessageMicro {
    public GetDownloadSignRsp() {}

    // repeated .GetDownloadSignRspItem rspList = 1;
    public static final int RSPLIST_FIELD_NUMBER = 1;
    private java.util.List<com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignRspItem> rspList_ =
      java.util.Collections.emptyList();
    public java.util.List<com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignRspItem> getRspListList() {
      return rspList_;
    }
    public int getRspListCount() { return rspList_.size(); }
    public com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignRspItem getRspList(int index) {
      return rspList_.get(index);
    }
    public GetDownloadSignRsp setRspList(int index, com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignRspItem value) {
      if (value == null) {
        throw new NullPointerException();
      }
      rspList_.set(index, value);
      return this;
    }
    public GetDownloadSignRsp addRspList(com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignRspItem value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (rspList_.isEmpty()) {
        rspList_ = new java.util.ArrayList<com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignRspItem>();
      }
      rspList_.add(value);
      return this;
    }
    public GetDownloadSignRsp clearRspList() {
      rspList_ = java.util.Collections.emptyList();
      return this;
    }

    public final GetDownloadSignRsp clear() {
      clearRspList();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      for (com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignRspItem element : getRspListList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      for (com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignRspItem element : getRspListList()) {
        output.writeMessage(1, element);
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      for (com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignRspItem element : getRspListList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(1, element);
      }
      cachedSize = size;
      return size;
    }

    @Override
    public GetDownloadSignRsp mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignRspItem value = new com.baidu.im.frame.pb.ProGetDownloadSign.GetDownloadSignRspItem();
            input.readMessage(value);
            addRspList(value);
            break;
          }
        }
      }
    }

    public static GetDownloadSignRsp parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (GetDownloadSignRsp) (new GetDownloadSignRsp().mergeFrom(data));
    }

    public static GetDownloadSignRsp parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new GetDownloadSignRsp().mergeFrom(input);
    }

  }

}
