/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.im.outapp.network.hichannel;

public class Channelinfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Channelinfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Channelinfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sessionJNI.delete_Channelinfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setChannelKey(String value) {
    sessionJNI.Channelinfo_channelKey_set(swigCPtr, this, value);
  }

  public String getChannelKey() {
    return sessionJNI.Channelinfo_channelKey_get(swigCPtr, this);
  }

  public void setExtraInfo(String value) {
    sessionJNI.Channelinfo_extraInfo_set(swigCPtr, this, value);
  }

  public String getExtraInfo() {
    return sessionJNI.Channelinfo_extraInfo_get(swigCPtr, this);
  }

  public void setDeviceToken(String value) {
    sessionJNI.Channelinfo_deviceToken_set(swigCPtr, this, value);
  }

  public String getDeviceToken() {
    return sessionJNI.Channelinfo_deviceToken_get(swigCPtr, this);
  }

  public void setNetwork(int value) {
    sessionJNI.Channelinfo_network_set(swigCPtr, this, value);
  }

  public int getNetwork() {
    return sessionJNI.Channelinfo_network_get(swigCPtr, this);
  }

  public void setApn(int value) {
    sessionJNI.Channelinfo_apn_set(swigCPtr, this, value);
  }

  public int getApn() {
    return sessionJNI.Channelinfo_apn_get(swigCPtr, this);
  }

  public void setOsversion(String value) {
    sessionJNI.Channelinfo_osversion_set(swigCPtr, this, value);
  }

  public String getOsversion() {
    return sessionJNI.Channelinfo_osversion_get(swigCPtr, this);
  }

  public void setSdkversion(String value) {
    sessionJNI.Channelinfo_sdkversion_set(swigCPtr, this, value);
  }

  public String getSdkversion() {
    return sessionJNI.Channelinfo_sdkversion_get(swigCPtr, this);
  }

  public Channelinfo() {
    this(sessionJNI.new_Channelinfo(), true);
  }

}
