/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.im.outapp.network.hichannel;

public class DirectMessage_T {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DirectMessage_T(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DirectMessage_T obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sessionJNI.delete_DirectMessage_T(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBuf(byte[] value) {
    sessionJNI.DirectMessage_T_buf_set(swigCPtr, this, value);
  }

  public byte[] getBuf() {
    return sessionJNI.DirectMessage_T_buf_get(swigCPtr, this);
  }

  public void setUlen(long value) {
    sessionJNI.DirectMessage_T_ulen_set(swigCPtr, this, value);
  }

  public long getUlen() {
    return sessionJNI.DirectMessage_T_ulen_get(swigCPtr, this);
  }

  public void setSeq(int value) {
    sessionJNI.DirectMessage_T_seq_set(swigCPtr, this, value);
  }

  public int getSeq() {
    return sessionJNI.DirectMessage_T_seq_get(swigCPtr, this);
  }

  public DirectMessage_T() {
    this(sessionJNI.new_DirectMessage_T(), true);
  }

}
