/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.im.outapp.network.hichannel;

public class HiCoreEnv {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected HiCoreEnv(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HiCoreEnv obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sessionJNI.delete_HiCoreEnv(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HiCoreEnv() {
    this(sessionJNI.new_HiCoreEnv(), true);
  }

  public boolean initEnv(String cfg_stream) {
    return sessionJNI.HiCoreEnv_initEnv(swigCPtr, this, cfg_stream);
  }

  public boolean deinitEnv() {
    return sessionJNI.HiCoreEnv_deinitEnv(swigCPtr, this);
  }

  public void initIpist(IpList iplist) {
    sessionJNI.HiCoreEnv_initIpist(swigCPtr, this, IpList.getCPtr(iplist), iplist);
  }

  public void initChannelInfo(Channelinfo channelinfo) {
    sessionJNI.HiCoreEnv_initChannelInfo(swigCPtr, this, Channelinfo.getCPtr(channelinfo), channelinfo);
  }

  public HiCoreSession createSession(String cfg_stream) {
    long cPtr = sessionJNI.HiCoreEnv_createSession(swigCPtr, this, cfg_stream);
    return (cPtr == 0) ? null : new HiCoreSession(cPtr, false);
  }

  public void destroySession(HiCoreSession pSess) {
    sessionJNI.HiCoreEnv_destroySession(swigCPtr, this, HiCoreSession.getCPtr(pSess), pSess);
  }

  public void enableLog(int enable) {
    sessionJNI.HiCoreEnv_enableLog(swigCPtr, this, enable);
  }

  public void set_log_callback(ILogCallback cb) {
    sessionJNI.HiCoreEnv_set_log_callback(swigCPtr, this, ILogCallback.getCPtr(cb), cb);
  }

}
