/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.im.outapp.network.hichannel;

public class ILogCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ILogCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ILogCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sessionJNI.delete_ILogCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    sessionJNI.ILogCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    sessionJNI.ILogCallback_change_ownership(this, swigCPtr, true);
  }

  public void d(byte[] data, int len) {
    sessionJNI.ILogCallback_d(swigCPtr, this, data, len);
  }

  public void i(byte[] data, int len) {
    sessionJNI.ILogCallback_i(swigCPtr, this, data, len);
  }

  public void w(byte[] data, int len) {
    sessionJNI.ILogCallback_w(swigCPtr, this, data, len);
  }

  public void e(byte[] data, int len) {
    sessionJNI.ILogCallback_e(swigCPtr, this, data, len);
  }

  public ILogCallback() {
    this(sessionJNI.new_ILogCallback(), true);
    sessionJNI.ILogCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
